name: CI Pipeline

on:
  pull_request:
    branches: [dev, staging, main]
    paths:
      - 'src/**'
      - 'public/**'
      - '*.json'
      - '*.js'
      - '*.jsx'
      - '!terraform/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 15

      - name: Install dependencies
        run: npm install

      - name: Install TypeScript ESLint dependencies
        run: |
          npm install --save-dev typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin

      - name: Run Prettier
        run: npx prettier --write .

      - name: Run ESLint
        run: npx eslint .

      - name: Run Tests
        run: npm test

      - name: Build App
        run: npm run build
