name: Deploy to S3

on:
  push:
    branches: [dev, staging, main]
    paths:
      - 'src/**'
      - 'public/**'
      - '*.json'
      - '*.js'
      - '*.jsx'
      - '!terraform/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 15

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy build/ to S3
        run: |
          BRANCH=$(echo "${GITHUB_REF##*/}")

          case "$BRANCH" in
            dev) BUCKET="cloudfront-s3-static-site-dev" ;;
            staging) BUCKET="cloudfront-s3-static-site-staging" ;;
            main) BUCKET="cloudfront-s3-static-site-prod" ;;
            *) echo "Unsupported branch: $BRANCH" && exit 1 ;;
          esac

          aws s3 sync build/ s3://$BUCKET --delete
